### ISSUE TITLE
Failed to load plugin promise: Cannot find module 'eslint-plugin-promise'

### ISSUE THREAD

**Issue by rasmuslundberg** [shinnn/vscode-standard#9]
Getting this error after update to 0.2.0

To reproduce i use latest vs code. Version 1.6.0 (1.6.0)
Using a mac, OSX el capitan. 
1. set "standard.enable": true in user settings
2. open any .js or .jsx file
3. Error pops up.

**Comment by shinnn** [comment]
Fixed in vscode-standard v0.2.1. Thanks for the report, @rasmuslundberg.

**Comment by rasmuslundberg** [comment]
I can confirm that its working now, thanks for the really super fast response @shinnn
